Repository jotoho/Einkaufshelfer, pull requests merged in 2025-02, with the labels that each got.

#3 chore(ci): add automated PR linting
  .github/workflows/ghpages.yaml
  .github/workflows/reuse-compliance.yaml
  .github/workflows/superlinter.yaml
  eslint.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#13 feat: add rudimentary dashboard page
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/autologin.ts
  src/config.ts
  src/dashboard.css
  src/dashboard.ts
  src/global.css
  src/types.ts
  uebersicht.html
Labels: enhancement, javascript

#14 chore(ci): remove super linter
  .github/workflows/superlinter.yaml
Labels: github_actions

#16 docs: document myself and @TimBeckmann as project-wide code owners
  .github/CODEOWNERS
Labels: documentation

#15 Vorläufiger Lösung für ein Login
  login.html
  src/login.css
  src/login.ts
Labels: enhancement

#17 feat: add standardized html pieces
  index.html
  package-lock.json
  package.json
  partials/meta.html
  partials/standardheader.html
  public/logout.svg
  src/dashboard.css
  src/global.css
  src/header.css
  src/header.ts
  uebersicht.html
  vite.config.js
Labels: enhancement

#19 fix: resolve build issues preventing vite from including all pages
  partials/standardheader.html
  src/header.css
  vite.config.js
Labels: bug

#20 fixes in login status detection + remove temporary autologin mechanism
  src/autologin.ts
  src/config.ts
  src/dashboard.ts
  src/login.ts
Labels: bug

#38 Account & team management
  index.html
  registration.html
  settings.html
  src/accountmgmt.css
  src/accountmgmt.ts
  src/config.ts
  src/global.css
  src/index.css
  src/index.ts
  src/notifications.ts
  src/register.css
  src/register.ts
  src/types.ts
Labels: enhancement

#41 feat: styled scrollbars
  src/global.css
Labels: enhancement

#42 feat: attempt to implement user household invitation with serverless function
  functions/userid-from-email/email_to_id_fn.py
  functions/userid-from-email/requirements.txt
  src/accountmgmt.ts
  src/config.ts
Labels: enhancement

#44 feat: (theoretically) implement kicking members + next try at invites
  functions/invite-to-team/add_to_team.py
  functions/invite-to-team/requirements.txt
  functions/userid-from-email/email_to_id_fn.py
  src/accountmgmt.ts
  src/config.ts
Labels: enhancement

#50 Finish household management features
  src/accountmgmt.css
  src/accountmgmt.ts
Labels: bug, enhancement

#51 feat: change email & passwort, improve types
  settings.html
  src/accountmgmt.ts
  src/dashboard.ts
  src/types.ts
Labels: enhancement

#52 feat: sort lists on dashboard
  src/dashboard.css
  src/dashboard.ts
Labels: enhancement

#59 feat: implementation for single list view
  liste.html
  partials/meta.html
  src/list.css
  src/list.ts
Labels: enhancement

#61 nutritional search
  .npmrc
  essensuche.html
  package-lock.json
  package.json
  partials/meta.html
  partials/standardheader.html
  src/config.ts
  src/foodsearch.css
  src/foodsearch.ts
  src/global.css
  src/header.ts
  src/notifications.ts
  tsconfig.json
  vite.config.js
Labels: enhancement

#73 Linking to Food Search + Final Cleanup on Dashboard
  partials/standardheader.html
  src/dashboard.css
  src/dashboard.ts
  src/header.ts
  uebersicht.html
Labels: enhancement, javascript

#76 feat: improvements to destructive account management operations
  settings.html
  src/accountmgmt.ts
Labels: bug, enhancement, javascript

#77 fix: resolve bad ordering of list elements on dashboard
  src/dashboard.ts
  uebersicht.html
Labels: bug
